### ISSUE TITLE
Начать кэшировать все talks в локальной БД

### ISSUE THREAD

**Issue by sintell** [hhru/meetup#3]
Сейчас на каждый запрос - мы ходим в Jira за списком существующих тем. Нужно их кешировать и обновлять кеш раз в минуту.

**Comment by ipetropolsky** [comment]
А какой RPS там? Может раз в минуту будут больше запросов, чем если при каждом заходе дёргать )

**Comment by sintell** [comment]
Там проблема не в том, что джира нагружается. На это ей плевать. Проблема в том, что джира медленная. До 700мс занимает один запрос. Из локальной базы (из какого-нибудь мемкэша) данные можно будет отдать за десятки мс.

**Comment by sintell** [comment]
Ещё вариант был на каждом запросе - ответ сохранять в кэш и при первом обращении отдать из кэша, а потом- динамически догружать
